### ISSUE TITLE
Configurar teste automático.

### ISSUE THREAD

**Issue by masmangan** [NatanaelKun/AstahPlugin#2]
Ver ocularium.

**Comment by NatanaelKun** [comment]
Arquivo Familia Exemplo atl.asta disponível em https://github.com/NatanaelKun/Families2Persons---Astah

**Comment by NatanaelKun** [comment]
Exemplos teste https://github.com/ocularium/ocularium/tree/master/simpleocl/src/test/java/ocularium

**Comment by NatanaelKun** [comment]
Nossos testes foram localizados em https://github.com/NatanaelKun/AstahPlugin/blob/master/families2persons/src/test/java/br/pucrs/esom/TemplateActionTest.java

**Comment by NatanaelKun** [comment]
Problemas ao executar mvn test e um erro na linha 261 foi encontrado do arquivo pom.xml

**Comment by NatanaelKun** [comment]
Para resolver o problema vai ser copiado uma variavel do arquivo pom.xml (https://github.com/ocularium/ocularium/blob/master/simpleocl/pom.xml) para o nosso arquivo pom.xml
